// Code generated by fuzzgen_test.go. DO NOT EDIT.

package fuzz

//////////////////////////////////////////
// TestOrGenerateExampleFuzzgenMessage vvv

// hello from example fuzzgen test.

// TestOrGenerateExampleFuzzgenMessage ^^^
//////////////////////////////////////////
